courses/urls.py
from django.urls import path
from . import views

app_name = 'saved_courses'

urlpatterns = [
    path('enroll/enroll/<int:kurs_id>/', views.enroll_course, name='enroll_course'),
    path('enrolls/', views.my_courses, name='my_courses'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from courses import views as course_views
from tests import views

urlpatterns = [
    path('', include('portal.urls')),
    path('courses/', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accound/', include('portal.urls')),
    path('register/', include('portal.urls')),
    path('enroll/', include(('courses.urls', 'portal'), namespace='portal')),
    path('saved_courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('course_view/<int:pk>/', course_views.view_course, name='view_course'),
    path('tests/', include('tests.urls', namespace='tests')),
]

portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/<int:pk>/', views.course_detail, name='course_detail'),
    path('accound/', views.accound, name='accound'),
    path('register/', views.register, name='register'),
]

users/urls.py
from django.urls import path
from . import views
# from .views import loginForm

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

portal/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Uzytkownicy(models.Model):
    id = models.AutoField(primary_key=True)
    imie = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=60)
    email = models.CharField(max_length=100, unique=True)
    haslo = models.CharField(max_length=255)
    status_uzytkownika = models.CharField(max_length=20)
    data_rejestracji = models.DateTimeField(auto_now_add=True)
    potwierdzony_email = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.imie} {self.nazwisko} ({self.email})"

class Kursy(models.Model):
    id = models.AutoField(primary_key=True)
    tytul = models.CharField(max_length=200)
    opis = models.TextField()
    dluzszyOpis = models.TextField(null=True, blank=True)
    tresc_kursu = models.TextField(null=True, blank=True)
    autor = models.ForeignKey(Uzytkownicy, on_delete=models.CASCADE, related_name='kursy')
    data_utworzenia = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.tytul

class Uprawnienia(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=50)
    opis = models.TextField()
    def __str__(self):
        return self.nazwa

class UprawnieniaUzytkownika(models.Model):
    uzytkownik = models.ForeignKey(Uzytkownicy, on_delete=models.CASCADE, related_name='uprawnienia_uzytkownika')
    uprawnienia = models.ForeignKey(Uprawnienia, on_delete=models.CASCADE, related_name='uprawnienia')

class Kursanci(models.Model):
    id = models.AutoField(primary_key=True)
    uzytkownik = models.ForeignKey(Uzytkownicy, on_delete=models.CASCADE, related_name='kursanci')
    kurs = models.ForeignKey(Kursy, on_delete=models.CASCADE, related_name='kursanci')
    postep = models.DecimalField(max_digits=5, decimal_places=2)

class Testy(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=200)
    prog_zdawalnosci = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    kurs = models.ForeignKey(Kursy, on_delete=models.CASCADE, related_name='testy')
    def __str__(self):
        return self.nazwa

class OcenyKursow(models.Model):
    id = models.AutoField(primary_key=True)
    uzytkownik = models.ForeignKey(Uzytkownicy, on_delete=models.CASCADE, related_name='oceny_kursow')
    kurs = models.ForeignKey(Kursy, on_delete=models.CASCADE, related_name='oceny_kursow')
    gwiazdki = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    komentarz = models.TextField()

class Pytania(models.Model):
    id = models.AutoField(primary_key=True)
    test = models.ForeignKey(Testy, on_delete=models.CASCADE, related_name='pytania')
    tresc = models.TextField()
    typ = models.CharField(max_length=50)
    punkty = models.IntegerField()

class Odpowiedzi(models.Model):
    id = models.AutoField(primary_key=True)
    pytanie = models.ForeignKey(Pytania, on_delete=models.CASCADE, related_name='odpowiedzi')
    tresc = models.TextField()
    poprawna = models.BooleanField(default=False)

class Lekcja(models.Model):
    kurs = models.ForeignKey(Kursy, related_name="lekcje", on_delete=models.CASCADE)
    tytul = models.CharField(max_length=255)
    tresc = models.TextField()
    order = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.order}. {self.tytul}"

portal/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Uzytkownicy

class RejestracjaForm(forms.ModelForm):
    username = forms.CharField(max_length=150, label='Nazwa użytkownika')
    password = forms.CharField(widget=forms.PasswordInput, label='Hasło')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Potwierdź hasło")
    imie = forms.CharField(max_length=50, label='Imię')
    nazwisko = forms.CharField(max_length=60, label='Nazwisko')
    email = forms.EmailField(label='Email')
    status_uzytkownika = forms.CharField(max_length=20, label="Status użytkownika")

    class Meta:
        model = Uzytkownicy
        fields = ['username', 'password', 'confirm_password', 'imie', 'nazwisko', 'email', 'status_uzytkownika']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Hasła nie są takie same")
        return cleaned_data
    
    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            first_name=self.cleaned_data['imie'],
            last_name=self.cleaned_data['nazwisko'],
            email=self.cleaned_data['email']
        )
        uzytkownik = Uzytkownicy(
            imie=self.cleaned_data['imie'],
            nazwisko=self.cleaned_data['nazwisko'],
            email=self.cleaned_data['email'],
            haslo=self.cleaned_data['password'],
            status_uzytkownika=self.cleaned_data['status_uzytkownika']
        )
        if commit:
            uzytkownik.save()
        return uzytkownik
    

portal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Kursy
from django.contrib import messages
from .forms import RejestracjaForm

def home(request):
    new_courses = Kursy.objects.order_by('-data_utworzenia')[:3]
    return render(request, 'portal/index.html', {'new_courses': new_courses})

def course_list(request):
    courses = Kursy.objects.all()
    return render(request, 'portal/course_list.html', {'courses': courses})

def course_detail(request, pk):
    course = get_object_or_404(Kursy, pk=pk)
    return render(request, 'portal/course_detail.html', {'course': course})

@login_required
def accound(request):
    user = request.user
    return render(request, 'portal/profile.html', {'user': user})

def register(request):
    if request.method == "POST":
        form = RejestracjaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Utworzono konto")
            return redirect('/users/login/')
    else:
        form = RejestracjaForm()
    return render(request, 'portal/register.html', {'form': form})

portal/templates/portal/course_detail.html
{% extends "layout.html" %}

{% block title %}
    Szczegóły kursu
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/kursy.css' %}">
{% endblock %}

{% block content %}
    <h2>Szegóły kursu</h2>
        {{ course.tytul }}
        {{ course.opis }}

        {% if user.is_authenticated %}
        <form action="{% url 'saved_courses:enroll_course' course.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Zapisz się na kurs</button>
        </form>
        {% else %}
        <p><a href="/users/login/">Zaloguj się</a>, aby zapisać się na kurs.</p>
        {% endif %}
{% endblock %}

portal/templates/portal/course_list.html
{% extends "layout.html" %}

{% block title %}
    Kursy
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/kursy.css' %}">
{% endblock %}

{% block content %}
    <h1>Dostępne kursy</h1>
    <div class="courses-container">
        {% for course in courses %}
            <div class="course-card">
                <h2>{{ course.tytul }}</h2>
                <p>{{ course.opis }}</p>
                <a class="btn" href="{% url 'course_detail' course.pk %}">Zobacz więcej</a>
            </div>
        {% empty %}
            <p>Brak dostępnych kursów</p>
        {% endfor %}
        </div>
{% endblock %}

portal/templates/portal/index.html
{% extends "layout.html" %}

{% block title %}
    Strona główna
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/style.css' %}">
{% endblock %}

{% block content %}
    <header>
        <h1>Portal e-learningowy</h1>
        <a href="{% url 'course_list' %}">Zobacz wszystkie Kursy</a>
    </header>
    <section class="new_courses">
        <h2>Najnowsze kursy</h2>
        <div class="courses-container">
            {% for course in new_courses %}
            <div class="course-card">
                <h2>{{ course.tytul }}</h2>
                <p>{{ course.opis }}</p>
                <a class="btn" href="{% url 'course_detail' course.pk %}">Zapisz się</a>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

portal/templates/portal/profile.html
{% extends "layout.html" %}

{% block title %}
    Profil użytkownika
{% endblock %}

{% block static %}
    {% load static %}
    <link href="https://unpkg.com/tailwindcss@1.9.6/dist/tailwind.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
   <div class="min-h-screen flex items-center justify-center">
    <div class="bg-white p-8 rounded-2xl space-y-2 shadow-md">
        <h1 class="text-2xl font-bold mb-6 text-gray-800">Profil użytkownika</h1>
        <p>Login: {{ user.username }}</p>
        <p>Imię: {{ user.first_name }}</p>
        <p>Nazwisko: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Status: {{ uzytkownik.status_uzytkownika }}</p>
        <p><a href="{% url 'saved_courses:my_courses' %}">Moje kursy</a></p>
     </div>
    </div>
{% endblock %}

portal/templates/portal/register.html
{% extends "layout.html" %}
{% block title %}
    Zarejestruj się
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/style.css' %}">
{% endblock %}

{% block content %}
  <div class="min-h-screen flex items-center justify-center">
    <div class="bg-white p-8 rounded-2xl">
        <h1 class="text-2xl font-bold mb-6 text-gray-800">Zarejestruj się</h1>

        <form method="post" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit"
                class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 rounded-lg transition-colors duration-200">
                Zarejestruj
            </button>
        </form>
    </div>
</div>
{% if messages %}
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
{% endif %}
{% endblock %}

portal/templates/portal/zapisane_kursy.html
{% extends "layout.html" %}

{% block title %}
    Twoje kursy
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/style.css' %}">
{% endblock %}

{% block content %}
    <div class="min-h-screen flex items-center justify-center">
    <div class="bg-white p-8 rounded-2xl">
        <h2 class="text-2xl font-bold mb-4">Moje kursy</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for e in enrollments %}
                <a class="cursor-pointer" href="{% url 'view_course' e.kurs.pk %}">
                <div class="border border-gray-300 rounded-lg p-4 shadow-sm transition duration-200 ease-in-out transform hover:scale-105">
                <h3 class="text-lg font-semibold text-gray-800">{{ e.kurs.tytul }}</h3>
            </div>
                </a>
            {% empty %}
                <p class="text-gray-500">Nie jesteś zapisany na żaden kurs.</p>
            {% endfor %}
        </div>
    </div>
</div>
    
{% endblock %}

portal/templates/portal/zapisano.html
{% extends "layout.html" %}

{% block title %}
    Zapisano!
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portal/style.css' %}">
{% endblock %}

{% block content %}
    <h1>Zapisano!</h1>
    <br>
    <p>zapisałeś się na kurs: <strong>{{ kurs.tytul }}</strong></p>
    <br>
    <a href="{% url 'course_detail' kurs.id %}" class="btn btn-primary">Powrót do kursu</a>
{% endblock %}