courses/urls.py
from django.urls import path
from . import views

app_name = 'saved_courses'

urlpatterns = [
    path('enroll/enroll/<int:kurs_id>/', views.enroll_course, name='enroll_course'),
    path('enrolls/', views.my_courses, name='my_courses'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from courses import views as course_views
from tests import views

urlpatterns = [
    path('', include('portal.urls')),
    path('courses/', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accound/', include('portal.urls')),
    path('register/', include('portal.urls')),
    path('enroll/', include(('courses.urls', 'portal'), namespace='portal')),
    path('saved_courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('course_view/<int:pk>/', course_views.view_course, name='view_course'),
    path('tests/', include('tests.urls', namespace='tests')),
]

users/urls.py
from django.urls import path
from . import views
# from .views import loginForm

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
    <link href="https://unpkg.com/tailwindcss@1.9.6/dist/tailwind.min.css" rel="stylesheet">
    {% block static %}

    {% endblock %}

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

       * {
           padding: 0;
           margin: 0;
           box-sizing: border-box;
           font-family: 'Poppins', sans-serif;
       }

       body {
           height: 100vh;
           background-color: #F4F4F4;
       }

       nav {
           display: flex;
           align-items: center;
           justify-content: space-between;
           height: 80px;
           padding: 0 40px;
       }

       nav h2 {
           color: rgb(0, 0, 0);
           font-weight: 700;
           margin-right: 6px;
       }

       nav ul {
           display: flex;
       }

       nav ul li {
           list-style: none;
       }

       nav ul li a {
           text-decoration: none;
           color: #000000;
           font-weight: 600;
           font-size: 1rem;
           margin-right: 0.6rem;
           transition: color 0.2s ease;
       }

       nav i:hover {
           color: #007BFF;
       }

       nav ul li:last-child a {
           margin: 0;
       }

       .menu-toggle {
           display: none;
           font-size: 1.8rem;
           cursor: pointer;
           color: #000;
       }

       @media screen and (max-width: 768px) {
           nav ul {
               position: absolute;
               top: 80px;
               left: 0;
               width: 100%;
               background-color: #fff;
               flex-direction: column;
               align-items: center;
               max-height: 0;
               overflow: hidden;
               transition: max-height 0.3s ease-in-out;
               box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
               z-index: 99;
           }

           nav ul li {
               margin: 15px 0;
           }

           .menu-toggle {
               display: block;
           }

           nav ul.active {
               max-height: 500px;
           }
       }
    </style>

    {% block extra_head %}{% endblock %}
</head>

<body>
    <nav>
        <h2><a href="/">Portal</a></h2>
        <div class="menu-toggle" id="mobile-menu-btn">
            <i class="fas fa-bars"></i>
        </div>
        <ul>
            <li><a class="tutaj" href="/"><i class="fa-solid fa-house"></i></a></li>
            <li><a href="/courses">Kursy</a></li>
            <li><a href="{% url 'saved_courses:my_courses' %}">Moje kursy</a></li>
            <li><a href="{% url 'users:login_view' %}">Zaloguj</a></li>
            <li><a href="/register">Zarejestruj</a></li>
            <li><form class="logout" action="{% url 'users:logout_view' %}" method="POST">
                {% csrf_token %}
                <button class="logout-btn">Wyloguj</button>
            </form></li>
            <li><a href="/accound"><i class="fas fa-user"></i></a></li>
        </ul>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script>
        const menuBtn = document.getElementById('mobile-menu-btn');
        const navUl = document.querySelector('nav ul');

        menuBtn.addEventListener('click', () => {
            navUl.classList.toggle('active');
        });
    </script>

</body>

</html>

templates/register.html
{% extends "layout.html" %}
{% block title %}
    Zarejestruj się
{% endblock %}
{% block content %}
<h2>Rejestracja</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Zarejestruj się</button>
</form>

{% if messages %}
  {% for message in messages %}
    <p>{{ message }}</p>
  {% endfor %}
{% endif %}
{% endblock %}